
ALTER TABLE public.rsos 
ADD COLUMN responsavel_id uuid REFERENCES public.hierarquia(id),
ADD COLUMN prefixo_viatura text,
ADD COLUMN prefixo_unidade text,
ADD COLUMN encarregado_id uuid REFERENCES public.hierarquia(id),
ADD COLUMN motorista_id uuid REFERENCES public.hierarquia(id),
ADD COLUMN homem3_id uuid REFERENCES public.hierarquia(id),
ADD COLUMN homem4_id uuid REFERENCES public.hierarquia(id),
ADD COLUMN homem5_id uuid REFERENCES public.hierarquia(id),
ADD COLUMN patrulha_inicio timestamptz,
ADD COLUMN patrulha_fim timestamptz,
ADD COLUMN armas_curtas integer DEFAULT 0,
ADD COLUMN armas_longas integer DEFAULT 0,
ADD COLUMN municoes_curtas text,
ADD COLUMN municoes_longas text,
ADD COLUMN drogas text,
ADD COLUMN bombas_caseiras text,
ADD COLUMN lockpicks text,
ADD COLUMN dinheiro_ilicito text,
ADD COLUMN outros_ilicitos text,
ADD COLUMN roubos_residencias integer DEFAULT 0,
ADD COLUMN caixa_eletronico integer DEFAULT 0,
ADD COLUMN roubo_veiculo integer DEFAULT 0,
ADD COLUMN pinote_apoio integer DEFAULT 0,
ADD COLUMN o11_disparo integer DEFAULT 0,
ADD COLUMN acoes_setada integer DEFAULT 0,
ADD COLUMN trafico_drogas integer DEFAULT 0,
ADD COLUMN chamados_190 integer DEFAULT 0,
ADD COLUMN prisoes_bopm text,
ADD COLUMN multas_descricao text,
ADD COLUMN outras_ocorrencias text,
ADD COLUMN motivo_rejeicao text;
